-- MySQL Script generated by MySQL Workbench

-- Tue Jul 19 20:28:06 2022

-- Model: New Model    Version: 1.0

-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;

SET
    @OLD_FOREIGN_KEY_CHECKS = @ @FOREIGN_KEY_CHECKS,
    FOREIGN_KEY_CHECKS = 0;

SET
    @OLD_SQL_MODE = @ @SQL_MODE,
    SQL_MODE = 'ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------

-- Schema mydb

-- -----------------------------------------------------

-- -----------------------------------------------------

-- Schema mydb

-- -----------------------------------------------------

CREATE SCHEMA IF NOT EXISTS `checkpoint_4` DEFAULT CHARACTER SET utf8;

USE `checkpoint_4` ;

DROP TABLE IF EXISTS `checkpoint_4`.`personality` ;

DROP TABLE IF EXISTS `checkpoint_4`.`user` ;

DROP TABLE IF EXISTS `checkpoint_4`.`language` ;

DROP TABLE IF EXISTS `checkpoint_4`.`Experience` ;

DROP TABLE IF EXISTS `checkpoint_4`.`techno` ;

DROP TABLE IF EXISTS `checkpoint_4`.`Projet` ;

DROP TABLE IF EXISTS `checkpoint_4`.`Projet_has_techno` ;

DROP TABLE IF EXISTS `checkpoint_4`.`personality_has_Projet` ;

-- -----------------------------------------------------

-- Table `mydb`.`personality`

-- -----------------------------------------------------

CREATE TABLE
    IF NOT EXISTS `checkpoint_4`.`personality` (
        `id` INT NOT NULL AUTO_INCREMENT,
        `Nom` VARCHAR(50) NOT NULL,
        `Prenom` VARCHAR(45) NOT NULL,
        `lien_git` VARCHAR(255) NOT NULL,
        `Lien_linkedin` VARCHAR(255) NOT NULL,
        `img_link` VARCHAR(255) NOT NULL,
        `img_alt` VARCHAR(255) NOT NULL,
        PRIMARY KEY (`id`),
        UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE
    ) ENGINE = InnoDB;

-- -----------------------------------------------------

-- Table `mydb`.`user`

-- -----------------------------------------------------

CREATE TABLE
    IF NOT EXISTS `mydb`.`user` (
        `id` INT NOT NULL AUTO_INCREMENT,
        `email` VARCHAR(255) NOT NULL,
        `hashed_password` VARCHAR(255) NOT NULL,
        PRIMARY KEY (`id`),
        UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE
    ) ENGINE = InnoDB;

-- -----------------------------------------------------

-- Table `mydb`.`language`

-- -----------------------------------------------------

CREATE TABLE
    IF NOT EXISTS `checkpoint_4`.`language` (
        `id` INT NOT NULL AUTO_INCREMENT,
        `languages` VARCHAR(2) NOT NULL,
        PRIMARY KEY (`id`),
        UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE
    ) ENGINE = InnoDB;

-- -----------------------------------------------------

-- Table `mydb`.`Experience`

-- -----------------------------------------------------

CREATE TABLE
    IF NOT EXISTS `checkpoint_4`.`Experience` (
        `id` INT NOT NULL AUTO_INCREMENT,
        `Titre` VARCHAR(100) NOT NULL,
        `description` VARCHAR(255) NOT NULL,
        `language_id` INT NOT NULL,
        PRIMARY KEY (`id`, `language_id`),
        UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
        INDEX `fk_Experience_language1_idx` (`language_id` ASC) VISIBLE,
        CONSTRAINT `fk_Experience_language1` FOREIGN KEY (`language_id`) REFERENCES `mydb`.`language` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION
    ) ENGINE = InnoDB;

-- -----------------------------------------------------

-- Table `mydb`.`techno`

-- -----------------------------------------------------

CREATE TABLE
    IF NOT EXISTS `checkpoint_4`.`techno` (
        `id` INT NOT NULL AUTO_INCREMENT,
        `titre` VARCHAR(100) NOT NULL,
        `img link` LONGTEXT NOT NULL,
        `img_alt` VARCHAR(255) NOT NULL,
        `language_id` INT NOT NULL,
        PRIMARY KEY (`id`, `language_id`),
        UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
        INDEX `fk_techno_language1_idx` (`language_id` ASC) VISIBLE,
        CONSTRAINT `fk_techno_language1` FOREIGN KEY (`language_id`) REFERENCES `mydb`.`language` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION
    ) ENGINE = InnoDB;

-- -----------------------------------------------------

-- Table `mydb`.`Projet`

-- -----------------------------------------------------

CREATE TABLE
    IF NOT EXISTS `mycheckpoint_4db`.`Projet` (
        `id` INT NOT NULL,
        `titre` VARCHAR(100) NOT NULL,
        `description` VARCHAR(252) NOT NULL,
        `language_id` INT NOT NULL,
        PRIMARY KEY (`id`, `language_id`),
        INDEX `fk_Projet_language1_idx` (`language_id` ASC) VISIBLE,
        CONSTRAINT `fk_Projet_language1` FOREIGN KEY (`language_id`) REFERENCES `mydb`.`language` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION
    ) ENGINE = InnoDB;

-- -----------------------------------------------------

-- Table `mydb`.`Projet_has_techno`

-- -----------------------------------------------------

CREATE TABLE
    IF NOT EXISTS `checkpoint_4`.`Projet_has_techno` (
        `Projet_id` INT NOT NULL,
        `techno_id` INT NOT NULL,
        PRIMARY KEY (`Projet_id`, `techno_id`),
        INDEX `fk_Projet_has_techno_techno1_idx` (`techno_id` ASC) VISIBLE,
        INDEX `fk_Projet_has_techno_Projet_idx` (`Projet_id` ASC) VISIBLE,
        CONSTRAINT `fk_Projet_has_techno_Projet` FOREIGN KEY (`Projet_id`) REFERENCES `mydb`.`Projet` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
        CONSTRAINT `fk_Projet_has_techno_techno1` FOREIGN KEY (`techno_id`) REFERENCES `mydb`.`techno` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION
    ) ENGINE = InnoDB;

-- -----------------------------------------------------

-- Table `mydb`.`personality_has_Projet`

-- -----------------------------------------------------

CREATE TABLE
    IF NOT EXISTS `checkpoint_4`.`personality_has_Projet` (
        `personality_id` INT NOT NULL,
        `Projet_id` INT NOT NULL,
        PRIMARY KEY (`personality_id`, `Projet_id`),
        INDEX `fk_personality_has_Projet_Projet1_idx` (`Projet_id` ASC) VISIBLE,
        INDEX `fk_personality_has_Projet_personality1_idx` (`personality_id` ASC) VISIBLE,
        CONSTRAINT `fk_personality_has_Projet_personality1` FOREIGN KEY (`personality_id`) REFERENCES `mydb`.`personality` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
        CONSTRAINT `fk_personality_has_Projet_Projet1` FOREIGN KEY (`Projet_id`) REFERENCES `mydb`.`Projet` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION
    ) ENGINE = InnoDB;

SET SQL_MODE=@OLD_SQL_MODE;

SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;

SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;